import type { Business } from './types';

/** city_id fixo só para mocks (`citySlug: carmo-do-rio-claro`). Em produção vem do banco. */
const MOCK_CRC_CITY_ID = 'a0000000-0000-4000-8000-000000000001';

/**
 * Sample seed de ~50 negócios reais de Carmo do Rio Claro/MG, normalizados
 * a partir dos dados públicos do cliqueiachei.com.br
 * (Pedraojs/papa-harlane no GitHub).
 *
 * Quando o Supabase estiver populado (via `scripts/import-cliqueiachei.ts`),
 * trocar `lib/businesses/queries.ts` para consultar o banco — não mexer aqui.
 */
export const MOCK_BUSINESSES: Business[] = [
  // ──────────────── Hospedagem & turismo ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-30531',
    citySlug: 'carmo-do-rio-claro',
    slug: 'cachoeira-da-usina',
    name: 'Cachoeira da Usina',
    shortDescription: 'Cachoeira em zona rural, ideal pra banho e dia em família.',
    address: 'Estrada Três Barras, 1',
    district: 'Zona Rural',
    categories: ['turismo', 'passeio'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.6,
    reviewsCount: 12,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-30530',
    citySlug: 'carmo-do-rio-claro',
    slug: 'serra-da-tormenta',
    name: 'Serra da Tormenta',
    shortDescription: 'Voo livre e ecoturismo na Serra.',
    description:
      'Ponto de voo livre tradicional da região. Operadores credenciados disponíveis para voos duplos.',
    address: 'Rua Padre Cipriano Campon, 1',
    district: 'Cascalho',
    whatsapp: '+55 35 99999-0001',
    categories: ['turismo', 'passeio'],
    status: 'published',
    plan: 'featured',
    featured: true,
    verified: true,
    claimed: true,
    rating: 4.9,
    reviewsCount: 87,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-30551',
    citySlug: 'carmo-do-rio-claro',
    slug: 'pesca-esportiva-furnas',
    name: 'Pesca Esportiva Furnas',
    shortDescription: 'Roteiros de pesca esportiva no Lago de Furnas.',
    description:
      'Guias credenciados para pesca de tucunaré, tambaqui e dourado. Saídas pela manhã com retorno no fim da tarde.',
    address: 'Lago de Furnas, 1',
    district: 'Zona Rural',
    whatsapp: '+55 35 99999-0002',
    categories: ['turismo', 'pesca'],
    amenities: ['estacionamento'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.8,
    reviewsCount: 41,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-30537',
    citySlug: 'carmo-do-rio-claro',
    slug: 'aterro-santa-quiteria',
    name: 'Aterro Santa Quitéria',
    shortDescription: 'Restaurante na beira da represa.',
    address: 'Rodovia MG 050, 1',
    district: 'Zona Rural',
    whatsapp: '+55 35 99999-0003',
    categories: ['turismo', 'restaurantes'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.4,
    reviewsCount: 9,
  },

  // ──────────────── Alimentação ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-pizz-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'pizzaria-do-centro',
    name: 'Pizzaria do Centro',
    shortDescription: 'Forno a lenha · disk-pizza · 30 sabores.',
    description: 'Tradicional pizzaria no centro, atendendo desde 1998. Aceita encomendas até 22h30.',
    address: 'Rua Sete de Setembro, 142',
    district: 'Centro',
    phone: '+55 35 3561-1010',
    whatsapp: '+55 35 99999-1010',
    categories: ['alimentacao', 'pizzaria'],
    amenities: ['delivery', 'retira_no_local', 'estacionamento'],
    paymentMethods: ['pix', 'credito', 'debito', 'dinheiro'],
    hours: {
      tue: [{ open: '18:00', close: '23:00' }],
      wed: [{ open: '18:00', close: '23:00' }],
      thu: [{ open: '18:00', close: '23:00' }],
      fri: [{ open: '18:00', close: '00:00' }],
      sat: [{ open: '18:00', close: '00:00' }],
      sun: [{ open: '18:00', close: '23:00' }],
    },
    status: 'published',
    plan: 'featured',
    featured: true,
    verified: true,
    claimed: true,
    rating: 4.7,
    reviewsCount: 132,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-rest-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'restaurante-mineirao',
    name: 'Restaurante Mineirão',
    shortDescription: 'Comida caseira mineira, almoço self-service.',
    address: 'Praça Cônego João Xavier, 88',
    district: 'Centro',
    phone: '+55 35 3561-2020',
    categories: ['alimentacao', 'restaurantes'],
    amenities: ['estacionamento', 'aceita_pet', 'retira_no_local'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    hours: {
      mon: [{ open: '11:00', close: '14:30' }],
      tue: [{ open: '11:00', close: '14:30' }],
      wed: [{ open: '11:00', close: '14:30' }],
      thu: [{ open: '11:00', close: '14:30' }],
      fri: [{ open: '11:00', close: '15:00' }],
      sat: [{ open: '11:00', close: '15:00' }],
    },
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.5,
    reviewsCount: 78,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-pad-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'padaria-carmo',
    name: 'Padaria Carmo',
    shortDescription: 'Pão fresquinho desde 5h. Café da manhã.',
    address: 'Rua Padre Cipriano Campon, 320',
    district: 'Centro',
    phone: '+55 35 3561-3030',
    whatsapp: '+55 35 99999-3030',
    categories: ['alimentacao', 'padaria'],
    amenities: ['retira_no_local', 'wifi'],
    paymentMethods: ['pix', 'credito', 'debito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.6,
    reviewsCount: 54,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-acg-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'acougue-do-mercado',
    name: 'Açougue do Mercado',
    shortDescription: 'Cortes especiais e churrasco. Atendimento por WhatsApp.',
    address: 'Mercado Municipal, Box 4',
    district: 'Centro',
    whatsapp: '+55 35 99999-4040',
    categories: ['alimentacao', 'acougue'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.3,
    reviewsCount: 21,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-bar-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'bar-do-ze',
    name: 'Bar do Zé',
    shortDescription: 'Cerveja gelada, petiscos, futebol nos finais de semana.',
    address: 'Rua João Pessoa, 45',
    district: 'Centro',
    whatsapp: '+55 35 99999-5050',
    categories: ['alimentacao', 'bar'],
    amenities: ['ar_condicionado', 'aceita_pet'],
    paymentMethods: ['pix', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.4,
    reviewsCount: 33,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-merc-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'supermercado-bom-preco',
    name: 'Supermercado Bom Preço',
    shortDescription: 'O maior sortimento da cidade. Estacionamento amplo.',
    address: 'Av. Brasil, 1.200',
    district: 'Centro',
    phone: '+55 35 3561-6000',
    categories: ['alimentacao', 'mercado'],
    amenities: ['estacionamento', 'acessivel'],
    paymentMethods: ['pix', 'credito', 'debito', 'dinheiro', 'vale_alimentacao'],
    status: 'published',
    plan: 'premium',
    featured: true,
    verified: true,
    claimed: true,
    rating: 4.4,
    reviewsCount: 210,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-sorv-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'sorveteria-da-praca',
    name: 'Sorveteria da Praça',
    shortDescription: 'Sorvete italiano artesanal · 40 sabores.',
    address: 'Praça Cônego João Xavier, 12',
    district: 'Centro',
    whatsapp: '+55 35 99999-7070',
    categories: ['alimentacao', 'sorveteria'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.8,
    reviewsCount: 96,
  },

  // ──────────────── Saúde ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-farm-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'farmacia-popular',
    name: 'Farmácia Popular',
    shortDescription: 'Medicamentos, manipulação, atendimento 24h aos finais de semana.',
    address: 'Rua Sete de Setembro, 250',
    district: 'Centro',
    phone: '+55 35 3561-1100',
    whatsapp: '+55 35 99999-1100',
    categories: ['saude', 'farmacia'],
    amenities: ['acessivel', 'estacionamento'],
    paymentMethods: ['pix', 'credito', 'debito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.7,
    reviewsCount: 142,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-clin-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'clinica-medica-carmo',
    name: 'Clínica Médica Carmo',
    shortDescription: 'Consultas, exames, ultrassom. Atende convênios.',
    address: 'Rua Monsenhor Mário, 620',
    district: 'Centro',
    phone: '+55 35 3561-2200',
    whatsapp: '+55 35 99999-2200',
    email: 'contato@clinicacarmo.com.br',
    categories: ['saude', 'clinica'],
    amenities: ['acessivel', 'estacionamento', 'ar_condicionado'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'featured',
    verified: true,
    claimed: true,
    rating: 4.9,
    reviewsCount: 67,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-dent-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'odonto-carmo',
    name: 'Odonto Carmo',
    shortDescription: 'Ortodontia, implantes, clareamento.',
    address: 'Av. Brasil, 800',
    district: 'Centro',
    phone: '+55 35 3561-3300',
    whatsapp: '+55 35 99999-3300',
    categories: ['saude', 'dentista'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.7,
    reviewsCount: 45,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-vet-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'pet-saude-carmo',
    name: 'Pet Saúde Carmo',
    shortDescription: 'Veterinária, banho e tosa, vacinas.',
    address: 'Rua Padre Cipriano Campon, 880',
    district: 'Centro',
    phone: '+55 35 3561-4400',
    whatsapp: '+55 35 99999-4400',
    categories: ['saude', 'veterinaria'],
    amenities: ['estacionamento', 'aceita_pet'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.8,
    reviewsCount: 89,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-acad-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'academia-fitness-carmo',
    name: 'Academia Fitness Carmo',
    shortDescription: 'Musculação, funcional, dança. Aulas com personal.',
    address: 'Rua João Pessoa, 320',
    district: 'Centro',
    phone: '+55 35 3561-5500',
    whatsapp: '+55 35 99999-5500',
    categories: ['saude', 'academia'],
    amenities: ['estacionamento', 'ar_condicionado', 'acessivel'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.6,
    reviewsCount: 58,
  },

  // ──────────────── Beleza ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-cab-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'salao-glamour',
    name: 'Salão Glamour',
    shortDescription: 'Cabelo, manicure, escova progressiva.',
    address: 'Rua Sete de Setembro, 450',
    district: 'Centro',
    whatsapp: '+55 35 99999-6600',
    categories: ['beleza', 'cabeleireiro', 'manicure'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.7,
    reviewsCount: 73,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-bar-bar-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'barbearia-do-zezao',
    name: 'Barbearia do Zezão',
    shortDescription: 'Barba e cabelo masculino. Café no atendimento.',
    address: 'Rua João Pessoa, 88',
    district: 'Centro',
    whatsapp: '+55 35 99999-7700',
    categories: ['beleza', 'barbearia'],
    paymentMethods: ['pix', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.9,
    reviewsCount: 142,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-est-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'estetica-bella',
    name: 'Estética Bella',
    shortDescription: 'Limpeza de pele, drenagem, depilação a laser.',
    address: 'Av. Brasil, 1.500',
    district: 'Centro',
    whatsapp: '+55 35 99999-8800',
    categories: ['beleza', 'estetica', 'depilacao'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'featured',
    verified: true,
    claimed: true,
    rating: 4.8,
    reviewsCount: 51,
  },

  // ──────────────── Casa ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-mov-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'moveis-planejados-canastra',
    name: 'Móveis Planejados Canastra',
    shortDescription: 'Marcenaria sob medida — cozinhas, dormitórios, escritórios.',
    address: 'Rod. MG 050, km 8',
    district: 'Distrito Industrial',
    phone: '+55 35 3561-9000',
    whatsapp: '+55 35 99999-9000',
    website: 'https://moveiscanastra.com.br',
    categories: ['casa', 'moveis'],
    amenities: ['estacionamento'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'featured',
    claimed: true,
    rating: 4.8,
    reviewsCount: 38,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-cons-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'casa-construcao',
    name: 'Casa & Construção',
    shortDescription: 'Material de construção, ferragens, tintas.',
    address: 'Av. Brasil, 2.300',
    district: 'Centro',
    phone: '+55 35 3561-1200',
    whatsapp: '+55 35 99998-1200',
    categories: ['casa', 'construcao'],
    amenities: ['estacionamento', 'delivery'],
    paymentMethods: ['pix', 'credito', 'debito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.5,
    reviewsCount: 92,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-eletro-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'lar-eletrodomesticos',
    name: 'Lar Eletrodomésticos',
    shortDescription: 'Geladeira, fogão, máquina de lavar — entrega em casa.',
    address: 'Rua Sete de Setembro, 95',
    district: 'Centro',
    phone: '+55 35 3561-1300',
    whatsapp: '+55 35 99998-1300',
    categories: ['casa', 'eletrodomestico'],
    amenities: ['delivery', 'estacionamento'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.4,
    reviewsCount: 47,
  },

  // ──────────────── Veículos ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-mec-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'auto-mecanica-do-toninho',
    name: 'Auto Mecânica do Toninho',
    shortDescription: 'Mecânica geral, suspensão, freios. 30 anos de tradição.',
    address: 'Av. Brasil, 1.890',
    district: 'Centro',
    phone: '+55 35 3561-1400',
    whatsapp: '+55 35 99998-1400',
    categories: ['veiculos', 'mecanica'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.7,
    reviewsCount: 64,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-borr-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'borracharia-pneu-bom',
    name: 'Borracharia Pneu Bom',
    shortDescription: 'Conserto e troca de pneus 24h. Atende pela MG-050.',
    address: 'Rod. MG 050, km 12',
    district: 'Zona Rural',
    whatsapp: '+55 35 99998-1500',
    categories: ['veiculos', 'borracheiro'],
    paymentMethods: ['pix', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.6,
    reviewsCount: 28,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-eletr-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'auto-eletrica-do-paulo',
    name: 'Auto Elétrica do Paulo',
    shortDescription: 'Elétrica automotiva, baterias, alarmes.',
    address: 'Rua João Pessoa, 410',
    district: 'Centro',
    phone: '+55 35 3561-1600',
    whatsapp: '+55 35 99998-1600',
    categories: ['veiculos', 'auto-eletrica'],
    paymentMethods: ['pix', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.5,
    reviewsCount: 19,
  },

  // ──────────────── Serviços ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-pedr-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'pedreiro-mestre-joao',
    name: 'Pedreiro Mestre João',
    shortDescription: 'Construção, reforma, acabamento. Orçamento grátis.',
    district: 'Centro',
    whatsapp: '+55 35 99998-1700',
    categories: ['servicos', 'pedreiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.8,
    reviewsCount: 22,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-jard-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'jardinagem-verde-vivo',
    name: 'Jardinagem Verde Vivo',
    shortDescription: 'Jardins, paisagismo, manutenção mensal.',
    district: 'Centro',
    whatsapp: '+55 35 99998-1800',
    categories: ['servicos', 'jardineiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.7,
    reviewsCount: 16,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-info-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'tech-info-carmo',
    name: 'Tech Info Carmo',
    shortDescription: 'Conserto de notebook, celular, instalação de redes.',
    address: 'Rua Sete de Setembro, 320',
    district: 'Centro',
    phone: '+55 35 3561-1900',
    whatsapp: '+55 35 99998-1900',
    categories: ['servicos', 'informatica', 'assistencia-tecnica'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.6,
    reviewsCount: 35,
  },

  // ──────────────── Compras ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-rou-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'fashion-store',
    name: 'Fashion Store',
    shortDescription: 'Roupas femininas e masculinas, marcas nacionais.',
    address: 'Praça Cônego João Xavier, 56',
    district: 'Centro',
    phone: '+55 35 3561-2100',
    whatsapp: '+55 35 99998-2100',
    instagram: 'fashionstore.crc',
    categories: ['compras', 'roupa'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.6,
    reviewsCount: 41,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-cal-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'sapataria-do-centro',
    name: 'Sapataria do Centro',
    shortDescription: 'Calçados, conserto, palmilhas sob medida.',
    address: 'Rua João Pessoa, 145',
    district: 'Centro',
    phone: '+55 35 3561-2200',
    categories: ['compras', 'calcado'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.4,
    reviewsCount: 18,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-flo-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'floricultura-violeta',
    name: 'Floricultura Violeta',
    shortDescription: 'Flores, buquês, decoração de eventos. Entrega na cidade.',
    address: 'Av. Brasil, 600',
    district: 'Centro',
    whatsapp: '+55 35 99998-2300',
    categories: ['compras', 'floricultura', 'flores-presentes'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.9,
    reviewsCount: 67,
  },

  // ──────────────── Educação ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-esc-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'colegio-monsenhor-mario',
    name: 'Colégio Monsenhor Mário',
    shortDescription: 'Educação Infantil, Fundamental e Médio. Tradição na cidade.',
    address: 'Rua Monsenhor Mário, 400',
    district: 'Cascalho',
    phone: '+55 35 3561-2500',
    categories: ['educacao', 'escola'],
    amenities: ['acessivel', 'estacionamento'],
    status: 'published',
    plan: 'free',
    verified: true,
    claimed: true,
    rating: 4.7,
    reviewsCount: 89,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-idi-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'cna-carmo',
    name: 'CNA Carmo do Rio Claro',
    shortDescription: 'Inglês e espanhol pra todas as idades.',
    address: 'Rua Sete de Setembro, 560',
    district: 'Centro',
    phone: '+55 35 3561-2600',
    whatsapp: '+55 35 99998-2600',
    categories: ['educacao', 'idiomas'],
    paymentMethods: ['pix', 'credito', 'debito'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.7,
    reviewsCount: 32,
  },

  // ──────────────── Lazer ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-fes-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'festas-do-sol',
    name: 'Festas do Sol',
    shortDescription: 'Aluguel de mesas, cadeiras, decoração e som.',
    address: 'Av. Brasil, 1.100',
    district: 'Centro',
    whatsapp: '+55 35 99998-2700',
    categories: ['lazer', 'festa-evento'],
    paymentMethods: ['pix', 'credito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.6,
    reviewsCount: 24,
  },
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-igr-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'matriz-nossa-senhora-do-carmo',
    name: 'Matriz Nossa Senhora do Carmo',
    shortDescription: 'Igreja matriz da cidade. Missas diárias e novena.',
    address: 'Praça Cônego João Xavier, s/n',
    district: 'Centro',
    phone: '+55 35 3561-2800',
    categories: ['lazer', 'igreja'],
    status: 'published',
    plan: 'free',
    claimed: false,
    rating: 4.9,
    reviewsCount: 156,
  },

  // ──────────────── Indústria ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-ind-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'laticinio-canastra',
    name: 'Laticínio Canastra',
    shortDescription: 'Queijo Canastra premiado, doce de leite, manteiga.',
    address: 'Rod. MG 050, km 18',
    district: 'Zona Rural',
    phone: '+55 35 3561-2900',
    whatsapp: '+55 35 99998-2900',
    website: 'https://laticiniocanastra.com.br',
    categories: ['industria', 'industria-comercio'],
    amenities: ['estacionamento'],
    paymentMethods: ['pix', 'credito'],
    status: 'published',
    plan: 'premium',
    featured: true,
    verified: true,
    claimed: true,
    rating: 4.9,
    reviewsCount: 287,
  },

  // ──────────────── Agro ────────────────
  {
    cityId: MOCK_CRC_CITY_ID,
    id: 'b-agro-1',
    citySlug: 'carmo-do-rio-claro',
    slug: 'agropecuaria-furnas',
    name: 'Agropecuária Furnas',
    shortDescription: 'Insumos agrícolas, ração, sementes, vacinas.',
    address: 'Rod. MG 050, km 5',
    district: 'Zona Rural',
    phone: '+55 35 3561-3000',
    whatsapp: '+55 35 99998-3000',
    categories: ['agro', 'animais'],
    amenities: ['estacionamento', 'delivery'],
    paymentMethods: ['pix', 'credito', 'debito', 'dinheiro'],
    status: 'published',
    plan: 'free',
    claimed: true,
    rating: 4.6,
    reviewsCount: 53,
  },
];
