import type { Catalog, DeliverySettings } from './catalog-types'

const BIZ_ID = 'bella-napoli-mock'

export const MOCK_DELIVERY: DeliverySettings = {
  deliveryEnabled: true,
  pickupEnabled: true,
  tableServiceEnabled: false,
  deliveryFee: 5,
  deliveryMinOrder: 30,
  deliveryTimeMin: 40,
  pickupTimeMin: 20,
  deliveryRadiusKm: 5,
  pixKey: '35991234567',
  acceptsCardOnDelivery: true,
  orderInstructions: 'Informe o endereço completo com número e bairro.',
}

export const MOCK_CATALOG: Catalog = {
  id: 'catalog-bella-napoli',
  businessId: BIZ_ID,
  name: 'Cardápio',
  catalogType: 'food_menu',
  sections: [
    {
      id: 'sec-salgadas',
      catalogId: 'catalog-bella-napoli',
      name: 'Pizzas salgadas',
      description: 'Massa artesanal, ingredientes frescos. Serve de 2 a 4 pessoas.',
      displayOrder: 0,
      items: [
        {
          id: 'item-margherita',
          sectionId: 'sec-salgadas',
          businessId: BIZ_ID,
          name: 'Margherita',
          description: 'Molho de tomate, muçarela fior di latte, tomate cereja e folhas de manjericão fresco.',
          price: 39.90,
          serves: '2–3 pessoas',
          prepTimeMin: 25,
          tags: ['vegetariano', 'destaque'],
          available: true,
          displayOrder: 0,
          optionGroups: [
            {
              id: 'og-tam-margherita',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena (4 fatias)', priceAdd: 0, available: true },
                { id: 'm', name: 'Média (6 fatias)', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande (8 fatias)', priceAdd: 20, available: true },
              ],
            },
            {
              id: 'og-borda-margherita',
              name: 'Borda recheada',
              description: 'Opcional',
              minChoices: 0,
              maxChoices: 1,
              values: [
                { id: 'sem', name: 'Sem borda', priceAdd: 0, available: true },
                { id: 'cheddar', name: 'Cheddar', priceAdd: 5, available: true },
                { id: 'catupiry', name: 'Catupiry', priceAdd: 5, available: true },
                { id: 'cream', name: 'Cream cheese', priceAdd: 5, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-calabresa',
          sectionId: 'sec-salgadas',
          businessId: BIZ_ID,
          name: 'Calabresa',
          description: 'Molho de tomate, muçarela, calabresa fatiada, cebola roxa e azeitonas pretas.',
          price: 39.90,
          tags: ['mais_pedido'],
          serves: '2–3 pessoas',
          prepTimeMin: 25,
          available: true,
          displayOrder: 1,
          optionGroups: [
            {
              id: 'og-tam-calabresa',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena (4 fatias)', priceAdd: 0, available: true },
                { id: 'm', name: 'Média (6 fatias)', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande (8 fatias)', priceAdd: 20, available: true },
              ],
            },
            {
              id: 'og-borda-calabresa',
              name: 'Borda recheada',
              description: 'Opcional',
              minChoices: 0,
              maxChoices: 1,
              values: [
                { id: 'sem', name: 'Sem borda', priceAdd: 0, available: true },
                { id: 'cheddar', name: 'Cheddar', priceAdd: 5, available: true },
                { id: 'catupiry', name: 'Catupiry', priceAdd: 5, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-portuguesa',
          sectionId: 'sec-salgadas',
          businessId: BIZ_ID,
          name: 'Portuguesa',
          description: 'Molho, muçarela, presunto, ovos, palmito, cebola e azeitonas.',
          price: 42.90,
          serves: '2–3 pessoas',
          prepTimeMin: 25,
          available: true,
          displayOrder: 2,
          optionGroups: [
            {
              id: 'og-tam-port',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-frango-cat',
          sectionId: 'sec-salgadas',
          businessId: BIZ_ID,
          name: 'Frango c/ catupiry',
          description: 'Frango desfiado temperado, catupiry cremoso, muçarela e milho verde.',
          price: 44.90,
          tags: ['destaque'],
          serves: '2–3 pessoas',
          prepTimeMin: 25,
          available: true,
          displayOrder: 3,
          optionGroups: [
            {
              id: 'og-tam-frango',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
            {
              id: 'og-borda-frango',
              name: 'Borda recheada',
              description: 'Opcional',
              minChoices: 0,
              maxChoices: 1,
              values: [
                { id: 'sem', name: 'Sem borda', priceAdd: 0, available: true },
                { id: 'cheddar', name: 'Cheddar', priceAdd: 5, available: true },
                { id: 'catupiry', name: 'Catupiry', priceAdd: 5, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-4queijos',
          sectionId: 'sec-salgadas',
          businessId: BIZ_ID,
          name: 'Quatro queijos',
          description: 'Muçarela, parmesão, gorgonzola e provolone. Para os amantes de queijo.',
          price: 45.90,
          serves: '2–3 pessoas',
          prepTimeMin: 25,
          tags: ['vegetariano'],
          available: true,
          displayOrder: 4,
          optionGroups: [
            {
              id: 'og-tam-4q',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-pepperoni',
          sectionId: 'sec-salgadas',
          businessId: BIZ_ID,
          name: 'Pepperoni',
          description: 'Molho de tomate, muçarela generosa e pepperoni italiano fatiado.',
          price: 46.90,
          serves: '2–3 pessoas',
          prepTimeMin: 25,
          tags: ['picante', 'novo'],
          available: true,
          displayOrder: 5,
          optionGroups: [
            {
              id: 'og-tam-pep',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'sec-doces',
      catalogId: 'catalog-bella-napoli',
      name: 'Pizzas doces',
      displayOrder: 1,
      items: [
        {
          id: 'item-brigadeiro',
          sectionId: 'sec-doces',
          businessId: BIZ_ID,
          name: 'Brigadeiro',
          description: 'Cobertura de brigadeiro cremoso, granulado e muçarela de leite.',
          price: 42.90,
          serves: '2–3 pessoas',
          prepTimeMin: 20,
          tags: ['destaque'],
          available: true,
          displayOrder: 0,
          optionGroups: [
            {
              id: 'og-tam-brig',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-romeu',
          sectionId: 'sec-doces',
          businessId: BIZ_ID,
          name: 'Romeu e Julieta',
          description: 'Muçarela, goiabada cremosa e um toque de manteiga. Clássico mineiro.',
          price: 39.90,
          serves: '2–3 pessoas',
          prepTimeMin: 20,
          tags: ['mais_pedido'],
          available: true,
          displayOrder: 1,
          optionGroups: [
            {
              id: 'og-tam-rj',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-choc-morango',
          sectionId: 'sec-doces',
          businessId: BIZ_ID,
          name: 'Chocolate c/ morango',
          description: 'Cobertura de chocolate meio amargo, morangos frescos e leite condensado.',
          price: 44.90,
          serves: '2–3 pessoas',
          prepTimeMin: 20,
          available: true,
          displayOrder: 2,
          optionGroups: [
            {
              id: 'og-tam-cm',
              name: 'Tamanho',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'p', name: 'Pequena', priceAdd: 0, available: true },
                { id: 'm', name: 'Média', priceAdd: 10, available: true },
                { id: 'g', name: 'Grande', priceAdd: 20, available: true },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'sec-bebidas',
      catalogId: 'catalog-bella-napoli',
      name: 'Bebidas',
      displayOrder: 2,
      items: [
        {
          id: 'item-coca2l',
          sectionId: 'sec-bebidas',
          businessId: BIZ_ID,
          name: 'Coca-Cola 2L',
          description: 'Garrafa PET 2 litros geladinha.',
          price: 12.00,
          available: true,
          displayOrder: 0,
          optionGroups: [],
        },
        {
          id: 'item-coca-lata',
          sectionId: 'sec-bebidas',
          businessId: BIZ_ID,
          name: 'Refrigerante lata 350ml',
          description: 'Coca-Cola, Guaraná, Fanta laranja ou Sprite. Diga qual na observação.',
          price: 7.00,
          available: true,
          displayOrder: 1,
          optionGroups: [
            {
              id: 'og-sabor-refri',
              name: 'Sabor',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'coca', name: 'Coca-Cola', priceAdd: 0, available: true },
                { id: 'guarana', name: 'Guaraná Antarctica', priceAdd: 0, available: true },
                { id: 'fanta', name: 'Fanta laranja', priceAdd: 0, available: true },
                { id: 'sprite', name: 'Sprite', priceAdd: 0, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-agua',
          sectionId: 'sec-bebidas',
          businessId: BIZ_ID,
          name: 'Água mineral 500ml',
          description: 'Sem gás. Geladinha.',
          price: 4.00,
          available: true,
          displayOrder: 2,
          optionGroups: [],
        },
        {
          id: 'item-suco',
          sectionId: 'sec-bebidas',
          businessId: BIZ_ID,
          name: 'Suco de laranja 1L',
          description: 'Natural, espremido na hora. Produção limitada.',
          price: 15.00,
          tags: ['mais_pedido'],
          available: true,
          displayOrder: 3,
          optionGroups: [],
        },
        {
          id: 'item-cerveja',
          sectionId: 'sec-bebidas',
          businessId: BIZ_ID,
          name: 'Heineken long neck 330ml',
          description: 'Long neck gelada.',
          price: 10.00,
          available: true,
          displayOrder: 4,
          optionGroups: [],
        },
      ],
    },
    {
      id: 'sec-combos',
      catalogId: 'catalog-bella-napoli',
      name: 'Combos',
      description: 'Combinações com desconto especial.',
      displayOrder: 3,
      items: [
        {
          id: 'item-combo-familia',
          sectionId: 'sec-combos',
          businessId: BIZ_ID,
          name: 'Combo Família',
          description: '1 pizza grande à sua escolha + 1 Coca-Cola 2L. Economize R$ 7,90.',
          price: 59.90,
          promotionalPrice: 52.00,
          serves: '3–4 pessoas',
          tags: ['destaque'],
          available: true,
          displayOrder: 0,
          optionGroups: [
            {
              id: 'og-sabor-familia',
              name: 'Sabor da pizza',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'margherita', name: 'Margherita', priceAdd: 0, available: true },
                { id: 'calabresa', name: 'Calabresa', priceAdd: 0, available: true },
                { id: 'portuguesa', name: 'Portuguesa', priceAdd: 3, available: true },
                { id: 'frango', name: 'Frango c/ catupiry', priceAdd: 5, available: true },
              ],
            },
          ],
        },
        {
          id: 'item-combo-casal',
          sectionId: 'sec-combos',
          businessId: BIZ_ID,
          name: 'Combo Casal',
          description: '1 pizza média à sua escolha + 2 latas de refrigerante. Perfeito pra dois.',
          price: 54.90,
          promotionalPrice: 49.90,
          serves: '2 pessoas',
          tags: ['mais_pedido'],
          available: true,
          displayOrder: 1,
          optionGroups: [
            {
              id: 'og-sabor-casal',
              name: 'Sabor da pizza',
              minChoices: 1,
              maxChoices: 1,
              values: [
                { id: 'margherita', name: 'Margherita', priceAdd: 0, available: true },
                { id: 'calabresa', name: 'Calabresa', priceAdd: 0, available: true },
                { id: 'portuguesa', name: 'Portuguesa', priceAdd: 3, available: true },
              ],
            },
          ],
        },
      ],
    },
  ],
}
