import type { Church, ChurchScheduleItem, WeekdayKey } from './types';

export const weekdayLabels: Record<WeekdayKey, string> = {
  segunda: 'Segunda-feira',
  terca: 'Terça-feira',
  quarta: 'Quarta-feira',
  quinta: 'Quinta-feira',
  sexta: 'Sexta-feira',
  sabado: 'Sábado',
  domingo: 'Domingo',
};

export const weekdayOrder: WeekdayKey[] = [
  'domingo',
  'segunda',
  'terca',
  'quarta',
  'quinta',
  'sexta',
  'sabado',
];

export const churches: Church[] = [
  {
    id: 'paroquia-nossa-senhora-do-carmo',
    slug: 'paroquia-nossa-senhora-do-carmo',
    name: 'Paróquia Nossa Senhora do Carmo (Matriz)',
    tradition: 'catolica',
    neighborhood: 'Centro',
    address: null,
    pastorName: 'Padre Gilmar Antônio Pimenta',
    phone: '(35) 99859-9661',
    instagram: '@paroquianscmg',
    shortDescription: 'Igreja Matriz e referência católica no centro de Carmo do Rio Claro.',
    claimed: false,
    featured: true,
  },
  {
    id: 'paroquia-sagrada-familia',
    slug: 'paroquia-sagrada-familia',
    name: 'Paróquia Sagrada Família',
    tradition: 'catolica',
    neighborhood: null,
    address: null,
    pastorName: 'Pe. Júlio César Martins',
    phone: null,
    instagram: '@paroquiasagradafamiliacrc',
    shortDescription: 'Comunidade paroquial com missas e formações ao longo da semana.',
    claimed: false,
    featured: true,
  },
  {
    id: 'igreja-batista-carmo',
    slug: 'igreja-batista-carmo',
    name: 'Igreja Batista em Carmo do Rio Claro',
    tradition: 'evangelica',
    neighborhood: null,
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@ibcarmo',
    shortDescription: 'Igreja evangélica com cultos regulares aos domingos.',
    claimed: false,
    featured: false,
  },
  {
    id: 'igreja-presbiteriana-independente',
    slug: 'igreja-presbiteriana-independente',
    name: 'Igreja Presbiteriana Independente',
    tradition: 'evangelica',
    neighborhood: null,
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@ipicarmo',
    shortDescription: 'Programação semanal com escola bíblica, culto e reunião de oração.',
    claimed: false,
    featured: false,
  },
  {
    id: 'igreja-evangelho-quadrangular',
    slug: 'igreja-evangelho-quadrangular',
    name: 'Igreja Evangelho Quadrangular',
    tradition: 'evangelica',
    neighborhood: null,
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@i.e.q_carmodorioclaro',
    shortDescription: 'Cultos semanais e escola bíblica à noite.',
    claimed: false,
    featured: false,
  },
  {
    id: 'assembleia-de-deus-sao-benedito',
    slug: 'assembleia-de-deus-sao-benedito',
    name: 'Assembleia de Deus (São Benedito)',
    tradition: 'evangelica',
    neighborhood: 'São Benedito',
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@ad.carmo',
    shortDescription: 'Cultos às quartas, sextas e domingos no bairro São Benedito.',
    claimed: false,
    featured: false,
  },
  {
    id: 'assembleia-de-deus-madureira',
    slug: 'assembleia-de-deus-madureira',
    name: 'Assembleia de Deus Madureira',
    tradition: 'evangelica',
    neighborhood: null,
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@admadureiracrc',
    shortDescription: 'Comunidade evangélica local com perfil público para reivindicação.',
    claimed: false,
    featured: false,
  },
  {
    id: 'igreja-adventista-setimo-dia',
    slug: 'igreja-adventista-setimo-dia',
    name: 'Igreja Adventista do Sétimo Dia',
    tradition: 'adventista',
    neighborhood: null,
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@iasd.crc',
    shortDescription: 'Comunidade adventista de Carmo do Rio Claro.',
    claimed: false,
    featured: false,
  },
  {
    id: 'igreja-casa-da-adoracao',
    slug: 'igreja-casa-da-adoracao',
    name: 'Igreja Casa da Adoração',
    tradition: 'evangelica',
    neighborhood: null,
    address: null,
    pastorName: null,
    phone: null,
    instagram: '@casadaadoracaocarmo',
    shortDescription: 'Cultos às terças e domingos, com programação noturna.',
    claimed: false,
    featured: false,
  },
];

export const churchSchedule: ChurchScheduleItem[] = [
  { id: 'matriz-dom-7', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'domingo', time: '07:00', title: 'Missa', note: null, sourceStatus: 'confirmed' },
  { id: 'matriz-dom-9', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'domingo', time: '09:00', title: 'Missa', note: null, sourceStatus: 'confirmed' },
  { id: 'matriz-dom-19', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'domingo', time: '19:00', title: 'Missa', note: null, sourceStatus: 'confirmed' },
  { id: 'matriz-seg-19', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'segunda', time: '19:00', title: 'Missa', note: 'Horário habitual', sourceStatus: 'needs_verification' },
  { id: 'matriz-terco-homens', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'terca', time: '19:00', title: 'Terço dos Homens', note: null, sourceStatus: 'confirmed' },
  { id: 'matriz-qua-19', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'quarta', time: '19:00', title: 'Missa', note: 'Programação comum das paróquias', sourceStatus: 'needs_verification' },
  { id: 'matriz-sab-1730', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'sabado', time: '17:30', title: 'Missa', note: 'Matriz e capelas', sourceStatus: 'needs_verification' },
  { id: 'matriz-sab-19', churchSlug: 'paroquia-nossa-senhora-do-carmo', weekday: 'sabado', time: '19:00', title: 'Missa', note: 'Matriz e capelas', sourceStatus: 'needs_verification' },
  { id: 'sagrada-dom-8', churchSlug: 'paroquia-sagrada-familia', weekday: 'domingo', time: '08:00', title: 'Missa', note: 'Verificar agenda paroquial', sourceStatus: 'needs_verification' },
  { id: 'sagrada-dom-17', churchSlug: 'paroquia-sagrada-familia', weekday: 'domingo', time: '17:00', title: 'Missa', note: 'Verificar agenda paroquial', sourceStatus: 'needs_verification' },
  { id: 'sagrada-dom-19', churchSlug: 'paroquia-sagrada-familia', weekday: 'domingo', time: '19:00', title: 'Missa', note: 'Verificar agenda paroquial', sourceStatus: 'needs_verification' },
  { id: 'sagrada-qua-19', churchSlug: 'paroquia-sagrada-familia', weekday: 'quarta', time: '19:00', title: 'Missa', note: 'Programação comum das paróquias', sourceStatus: 'needs_verification' },
  { id: 'sagrada-sab-17', churchSlug: 'paroquia-sagrada-familia', weekday: 'sabado', time: '17:00', title: 'Missa no Centro de Formação', note: null, sourceStatus: 'confirmed' },
  { id: 'sagrada-sab-19', churchSlug: 'paroquia-sagrada-familia', weekday: 'sabado', time: '19:00', title: 'Missa', note: null, sourceStatus: 'confirmed' },
  { id: 'batista-dom-9', churchSlug: 'igreja-batista-carmo', weekday: 'domingo', time: '09:00', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'batista-dom-19', churchSlug: 'igreja-batista-carmo', weekday: 'domingo', time: '19:00', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'batista-qui-19', churchSlug: 'igreja-batista-carmo', weekday: 'quinta', time: '19:00', title: 'Culto', note: null, sourceStatus: 'needs_verification' },
  { id: 'ipi-dom-ebd', churchSlug: 'igreja-presbiteriana-independente', weekday: 'domingo', time: '09:00', title: 'EBD', note: null, sourceStatus: 'confirmed' },
  { id: 'ipi-dom-culto', churchSlug: 'igreja-presbiteriana-independente', weekday: 'domingo', time: '19:30', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'ipi-qui-oracao', churchSlug: 'igreja-presbiteriana-independente', weekday: 'quinta', time: '20:00', title: 'Oração', note: null, sourceStatus: 'confirmed' },
  { id: 'quadrangular-dom', churchSlug: 'igreja-evangelho-quadrangular', weekday: 'domingo', time: '19:00', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'quadrangular-seg', churchSlug: 'igreja-evangelho-quadrangular', weekday: 'segunda', time: '19:30', title: 'Escola Bíblica', note: null, sourceStatus: 'confirmed' },
  { id: 'quadrangular-qua', churchSlug: 'igreja-evangelho-quadrangular', weekday: 'quarta', time: '19:30', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'ad-sao-benedito-dom', churchSlug: 'assembleia-de-deus-sao-benedito', weekday: 'domingo', time: '18:30', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'ad-sao-benedito-ter', churchSlug: 'assembleia-de-deus-sao-benedito', weekday: 'terca', time: '19:30', title: 'Culto', note: null, sourceStatus: 'needs_verification' },
  { id: 'ad-sao-benedito-qua', churchSlug: 'assembleia-de-deus-sao-benedito', weekday: 'quarta', time: '19:30', title: 'Culto de oração e libertação', note: null, sourceStatus: 'confirmed' },
  { id: 'ad-sao-benedito-qui', churchSlug: 'assembleia-de-deus-sao-benedito', weekday: 'quinta', time: '19:30', title: 'Culto', note: null, sourceStatus: 'needs_verification' },
  { id: 'ad-sao-benedito-sex', churchSlug: 'assembleia-de-deus-sao-benedito', weekday: 'sexta', time: '19:30', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'ad-sao-benedito-sab', churchSlug: 'assembleia-de-deus-sao-benedito', weekday: 'sabado', time: '19:00', title: 'Culto', note: null, sourceStatus: 'needs_verification' },
  { id: 'casa-dom', churchSlug: 'igreja-casa-da-adoracao', weekday: 'domingo', time: '18:30', title: 'Culto', note: null, sourceStatus: 'confirmed' },
  { id: 'casa-ter', churchSlug: 'igreja-casa-da-adoracao', weekday: 'terca', time: '19:30', title: 'Culto', note: null, sourceStatus: 'confirmed' },
];
