import { Ionicons } from '@expo/vector-icons';

type IoniconName = keyof typeof Ionicons.glyphMap;

/**
 * Lucide icon name (stored in business_categories.icon) → closest Ionicons.
 * Não precisa ser exaustivo — fallback é 'pricetag'.
 */
const LUCIDE_TO_IONICONS: Record<string, IoniconName> = {
  Activity: 'pulse',
  Antenna: 'radio',
  Beef: 'restaurant',
  Bed: 'bed',
  BedDouble: 'bed',
  Brain: 'bulb',
  BriefcaseMedical: 'medkit',
  Briefcase: 'briefcase',
  Building2: 'business',
  Candy: 'ice-cream',
  Car: 'car',
  CarFront: 'car-sport',
  Church: 'flower',
  Cog: 'cog',
  Cookie: 'cafe',
  Crown: 'star',
  Disc: 'disc',
  Droplets: 'water',
  Dumbbell: 'barbell',
  Eye: 'eye',
  Factory: 'business',
  Fish: 'fish',
  FlaskConical: 'flask',
  Flame: 'flame',
  Flower: 'flower',
  Flower2: 'flower',
  Footprints: 'footsteps',
  GraduationCap: 'school',
  HardHat: 'construct',
  HeartPulse: 'heart',
  Home: 'home',
  House: 'home',
  IceCreamCone: 'ice-cream',
  Lamp: 'bulb',
  Languages: 'language',
  Laptop: 'laptop',
  Map: 'map',
  Microscope: 'flask',
  MountainSnow: 'triangle',
  Package: 'cube',
  PaintBucket: 'color-fill',
  PaintRoller: 'brush',
  Palette: 'color-palette',
  PartyPopper: 'sparkles',
  PawPrint: 'paw',
  Pill: 'medical',
  Pizza: 'pizza',
  Plug: 'flash',
  Sandwich: 'fast-food',
  School: 'school',
  Scissors: 'cut',
  ShoppingBag: 'bag',
  ShoppingCart: 'cart',
  Shirt: 'shirt',
  Smile: 'happy',
  Sofa: 'bed',
  Sparkles: 'sparkles',
  Sprout: 'leaf',
  Square: 'square',
  Stethoscope: 'medkit',
  Store: 'storefront',
  Tv: 'tv',
  TreePalm: 'leaf',
  Utensils: 'restaurant',
  UtensilsCrossed: 'restaurant',
  WashingMachine: 'water',
  Wind: 'cloudy',
  Wine: 'wine',
  Wrench: 'construct',
  Zap: 'flash',
};

export function ioniconForCategory(lucideName: string | null | undefined): IoniconName {
  if (!lucideName) return 'pricetag';
  return LUCIDE_TO_IONICONS[lucideName] ?? 'pricetag';
}
